// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ieugmthivkvvhlmiihie.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlldWdtdGhpdmt2dmhsbWlpaGllIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczMzEwNTMsImV4cCI6MjA3MjkwNzA1M30.z_CekPgk13a_52rJ0U0jcAL99PC9vdhF9V5QY1ZhreM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});